USE [master]
GO
/****** Object:  Database [cobranzas]    Script Date: 11/10/2023 14:57:49 ******/
CREATE DATABASE [cobranzas]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'cobranzas', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\cobranzas.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'cobranzas_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\cobranzas_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [cobranzas] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [cobranzas].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [cobranzas] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [cobranzas] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [cobranzas] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [cobranzas] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [cobranzas] SET ARITHABORT OFF 
GO
ALTER DATABASE [cobranzas] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [cobranzas] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [cobranzas] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [cobranzas] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [cobranzas] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [cobranzas] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [cobranzas] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [cobranzas] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [cobranzas] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [cobranzas] SET  DISABLE_BROKER 
GO
ALTER DATABASE [cobranzas] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [cobranzas] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [cobranzas] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [cobranzas] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [cobranzas] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [cobranzas] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [cobranzas] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [cobranzas] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [cobranzas] SET  MULTI_USER 
GO
ALTER DATABASE [cobranzas] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [cobranzas] SET DB_CHAINING OFF 
GO
ALTER DATABASE [cobranzas] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [cobranzas] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [cobranzas] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [cobranzas] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [cobranzas] SET QUERY_STORE = ON
GO
ALTER DATABASE [cobranzas] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [cobranzas]
GO
/****** Object:  Table [dbo].[Clientes]    Script Date: 11/10/2023 14:57:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Clientes](
	[idCliente] [int] IDENTITY(1,1) NOT NULL,
	[apellido] [varchar](50) NULL,
	[nombre] [varchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[idCliente] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Cobranzas]    Script Date: 11/10/2023 14:57:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Cobranzas](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[fecha] [date] NOT NULL,
	[idCliente] [int] NULL,
	[monto] [decimal](10, 2) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[Clientes] ON 
GO
INSERT [dbo].[Clientes] ([idCliente], [apellido], [nombre]) VALUES (1, N'Verga Lobos', N'Agustin')
GO
INSERT [dbo].[Clientes] ([idCliente], [apellido], [nombre]) VALUES (2, N'Paredero', N'Thomas')
GO
INSERT [dbo].[Clientes] ([idCliente], [apellido], [nombre]) VALUES (3, N'Lobos', N'Cristina')
GO
INSERT [dbo].[Clientes] ([idCliente], [apellido], [nombre]) VALUES (6, N'Farha', N'Benjamin')
GO
INSERT [dbo].[Clientes] ([idCliente], [apellido], [nombre]) VALUES (7, N'Verga', N'Abel')
GO
SET IDENTITY_INSERT [dbo].[Clientes] OFF
GO
SET IDENTITY_INSERT [dbo].[Cobranzas] ON 
GO
INSERT [dbo].[Cobranzas] ([id], [fecha], [idCliente], [monto]) VALUES (2, CAST(N'2023-05-12' AS Date), 6, CAST(5000.00 AS Decimal(10, 2)))
GO
INSERT [dbo].[Cobranzas] ([id], [fecha], [idCliente], [monto]) VALUES (3, CAST(N'2023-11-06' AS Date), 3, CAST(400.00 AS Decimal(10, 2)))
GO
INSERT [dbo].[Cobranzas] ([id], [fecha], [idCliente], [monto]) VALUES (8, CAST(N'2022-05-21' AS Date), 2, CAST(1300.00 AS Decimal(10, 2)))
GO
INSERT [dbo].[Cobranzas] ([id], [fecha], [idCliente], [monto]) VALUES (11, CAST(N'2023-04-07' AS Date), 7, CAST(2500.00 AS Decimal(10, 2)))
GO
INSERT [dbo].[Cobranzas] ([id], [fecha], [idCliente], [monto]) VALUES (12, CAST(N'2023-07-12' AS Date), 1, CAST(3050.00 AS Decimal(10, 2)))
GO
SET IDENTITY_INSERT [dbo].[Cobranzas] OFF
GO
ALTER TABLE [dbo].[Cobranzas]  WITH CHECK ADD FOREIGN KEY([idCliente])
REFERENCES [dbo].[Clientes] ([idCliente])
GO
USE [master]
GO
ALTER DATABASE [cobranzas] SET  READ_WRITE 
GO
